---
title: "AFL Browne-Low Raw Stats, Analytics, and Pre Processing"
output: html_notebook
---
This project was conducted by Thomas Johnstone, Richard, and Luke Mason, with supervision from RMIT Lecturer Dr Haydar Demirhan Bayesian Statistics 2022.


This R Notebook is responsible for pre processing the AFL stats so that they can be consumed by the JAGS model.
## Imports
```{r}
library(tidyr)
```


## Load in the training set
```{r}
raw_stats = read.csv("../../data/train_set.csv")
```


Create the list of round names
```{r}
# Create initial list of valid round names.
valid_round_names <- c()

# Create 23 round names.
for (num in 1:23) {
  # Append round names to valid round name list
  valid_round_names <- c(valid_round_names, paste("R", num, sep=""))
}

# Display.
valid_round_names
```

```{r}

# Set of column names that are not numerical, or do not contribute to the calculation of brownlow points
drops <- c("gameId","gameNumber", "Subs", "year", "team", "X..Played", "playerId", "displayName", "round")

# Drop these column names from the raw stats into filtered dataframe.
filtered_df <- raw_stats[ , !(names(raw_stats) %in% drops)]

# Aggregate all fields in the filtered data frame, but group them by the list of values in field columns:
# - playerId; so that all games of the player are aggregated together by mean
# - displayName; so that we can have the name of the player during data analysis
# - round; so that the player's games are not aggregated into 1 row, but instead 1 row per round.
agg = aggregate(filtered_df, by=list(raw_stats$playerId, raw_stats$displayName, raw_stats$round), FUN = mean)

# Remove rows who's round is not in the list of valid round names
# This is because the finals rounds exist after round 22 and there are no brownlow points assigned to players during these games, which makes these rows redundant.
df1 <- agg[ agg$Group.3 %in% valid_round_names, ]

stat_cols = c("Behinds", "Bounces", "Brownlow.Votes", "Clangers", "Clearances", "Contested.Marks", "Contested.Possessions",
    "Disposals", "Frees", "Frees.Against", "Goal.Assists", "Goals", "Handballs",
    "Hit.Outs", "Inside.50s", "Kicks", "Marks", "Marks.Inside.50", "One.Percenters", "Rebounds",
    "Tackles", "Uncontested.Possessions")

df2 = pivot_longer(df1, names_to="stat", values_to="value", cols=all_of(stat_cols))
df3 = pivot_wider(df2, id_cols = c("Group.1", "Group.2", "stat"), names_from = "Group.3")

# Order the columns
col_order = c("Group.1", "Group.2", "stat", valid_round_names)
df4 <- df3[, col_order]

# Rename columns
names(df4)[names(df4) == 'Group.1'] <- 'playerId'
names(df4)[names(df4) == 'Group.2'] <- 'displayName'

df4
```




```{r}
# Rename columns
names(df1)[names(df1) == 'Group.1'] <- 'playerId'
names(df1)[names(df1) == 'Group.2'] <- 'displayName'
names(df1)[names(df1) == 'Group.3'] <- 'round'

stat_df <- df1[order(df1$playerId, df1$displayName, df1$round),]
stat_df
```
```{r}
filtered_df2 <- filtered_df[ , !(names(filtered_df) %in% c("rounds"))]
# Aggregate all fields in the filtered data frame, but group them by the list of values in field columns:
# - playerId; so that all games of the player are aggregated together by mean
# - displayName; so that we can have the name of the player during data analysis
# - round; so that the player's games are not aggregated into 1 row, but instead 1 row per round.
per_player_agg = aggregate(filtered_df, by=list(raw_stats$playerId, raw_stats$displayName), FUN = mean)

# Rename columns
names(per_player_agg)[names(per_player_agg) == 'Group.1'] <- 'playerId'
names(per_player_agg)[names(per_player_agg) == 'Group.2'] <- 'displayName'

ppa <- per_player_agg[order(per_player_agg$playerId, per_player_agg$displayName),]
ppa
```

## Save datasets
```{r}
write.csv(df4, "../../data/train_preprocessed_rounds.csv", row.names=FALSE)
write.csv(stat_df, "../../data/train_preprocessed_stats_per_round.csv", row.names=FALSE)
write.csv(per_player_agg, "../../data/train_preprocessed_stats_per_player.csv", row.names=FALSE)
```
    





